### ISSUE TITLE
Missing addon 

### ISSUE THREAD

**Issue by PauleyT** [Spearhead-Gaming-Milsim/Operation-Free-bird#1]
idk what "L_ES_ES_sys" is but it needs to be removed, and when i try and remove it it breaks the mission.

**Comment by coachwn** [comment]
Yeah it depends on what you started building the mission with. Sometimes you have to break it down and merge it with a new mission and it should fix it since it after you remove it.

**Comment by PauleyT** [comment]
I sent the mission file to jmaster to look at and thats in the mod list and when i remove every piece of it from the mission.sqf it breeaks the mission and wont load
